### ISSUE TITLE
Usage Example?

### ISSUE THREAD

**Issue by cemerson** [nesterovsky-bros/BidiVisualConverter#1]
Hey there,
I'm not 100% sure what this thing does yet but I'm wrestling with RTL text stuff with C# right now so would love to see an example of how this is used in case it is something I can use. Any chance you could throw a syntax example or two in the ReadMe?

Thanks.

**Comment by vnesterovsky** [comment]
Please see https://github.com/nesterovsky-bros/BidiVisualConverter/blob/master/Tests/UnitTest.cs
I've added a link to readme.

Thanks.
